"""empty message

Revision ID: 8e3037c3b1df
Revises: 2b563013d888
Create Date: 2018-07-29 21:58:01.219256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e3037c3b1df'
down_revision = '2b563013d888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('cms_user', sa.Column('last_login_time', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'cms_user_role', 'cms_role', ['role_id'], ['id'])
    op.create_foreign_key(None, 'cms_user_role', 'cms_user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cms_user_role', type_='foreignkey')
    op.drop_constraint(None, 'cms_user_role', type_='foreignkey')
    op.drop_column('cms_user', 'last_login_time')
    op.drop_column('cms_user', 'is_active')
    # ### end Alembic commands ###
