#coding:utf8

CMS_SESSION_ID = 'suibianxie'
FRONT_SESSION_ID = 'suibianxiea'

ACCESS_KEY_ID = "LTAIdOdRfLnslYja"
ACCESS_KEY_SECRET = "p9Q3t1GYpHjdtNB7RYaqbHgw3UASfC"
ALIYUN_SIGN_NAME = "李垒"
ALIYUN_TEMPLATE_CODE = "SMS_140850049"

QINIU_ACCESS_KEY = 'SXJAGOM6nPxMAInwr3y5yy8cuGdQeIHIKsyMsvqt'
QINIU_SECRET_KEY = 'uoYTDGLeAbrzEcQRhuRyYhB_In8RF2ageTqE7QK4'

# QINIU_ACCESS_KEY = 'NYf7olCvVv1d4vsUdojJKrRgnAB5CbIZH-H4lonW'
# QINIU_SECRET_KEY = 'LOXl9kWHU9bglKJxidzwezNhhJvEYzt6SvvlbKuZ'

PAGE_NUM = 10

TOTAL_POST_COUNT_KEY = 'total_post_count'
